apiVersion: v1
kind: ConfigMap
metadata:
  name: daily-basket-api-config
  namespace: daily-basket
  labels:
    app.kubernetes.io/name: daily-basket-api
    app.kubernetes.io/part-of: daily-basket-platform
data:
  NODE_ENV: "production"
  PORT: "4000"
  REDIS_HOST: "redis-master.daily-basket.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  ENABLE_SWAGGER: "true"
  CORS_ORIGINS: "*"
