apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daily-basket-ingress
  namespace: daily-basket
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "65"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "65"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/websocket-services: "daily-basket-api-service"
spec:
  tls:
    - hosts:
        - api.dailybasket.in
      secretName: dailybasket-api-tls
  rules:
    - host: api.dailybasket.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daily-basket-api-service
                port:
                  number: 80
