apiVersion: v1
kind: Secret
metadata:
  name: daily-basket-api-secrets
  namespace: daily-basket
  labels:
    app.kubernetes.io/name: daily-basket-api
    app.kubernetes.io/part-of: daily-basket-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:dailybasket_prod_pwd@postgres-primary.daily-basket.svc.cluster.local:5432/dailybasket_prod?schema=public&sslmode=prefer&connection_limit=50"
  JWT_SECRET: "db_jwt_super_secret_enterprise_key_2026_prod_secure_token"
  REDIS_PASSWORD: "dailybasket_redis_secure_pass"
