/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'secondary': '#515f74',
        'background': '#f7f9fb',
        'on-primary-fixed-variant': '#00531a',
        'on-secondary-fixed-variant': '#3a485c',
        'on-surface-subtle': '#64748b',
        'on-surface-variant': '#3f4a3d',
        'on-surface': '#191c1e',
        'tertiary': '#a42f57',
        'surface-variant': '#e0e3e5',
        'status-success': '#15803d',
        'on-secondary-fixed': '#0d1c2f',
        'on-error': '#ffffff',
        'on-secondary-container': '#57657b',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed-dim': '#ffb1c3',
        'status-warning': '#b45309',
        'status-error': '#b91c1c',
        'primary-fixed-dim': '#70dd7a',
        'on-tertiary-container': '#fffbff',
        'inverse-primary': '#70dd7a',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2d3133',
        'surface-container-low': '#f2f4f6',
        'surface-tint': '#006e25',
        'outline': '#6e7a6c',
        'surface-container': '#eceef0',
        'secondary-fixed': '#d5e3fd',
        'primary-fixed': '#8cfa93',
        'tertiary-fixed': '#ffd9e0',
        'surface-dim': '#d8dadc',
        'surface': '#f7f9fb',
        'error': '#ba1a1a',
        'on-primary-fixed': '#002106',
        'on-background': '#191c1e',
        'tertiary-container': '#c4486f',
        'primary': '#006b23',
        'secondary-fixed-dim': '#b9c7e0',
        'on-tertiary-fixed': '#3f0019',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'status-info': '#0369a1',
        'secondary-container': '#d5e3fd',
        'on-primary-container': '#f7fff2',
        'on-tertiary-fixed-variant': '#881842',
        'primary-container': '#078730',
        'surface-bright': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'outline-variant': '#becab9',
        'inverse-on-surface': '#eff1f3',
        'surface-container-high': '#e6e8ea',
        brand: {
          500: '#006b23',
          600: '#078730',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
};
